services:
  - type: web
    name: quizzap
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MY_TOKEN
        sync: false  # This will prompt you to enter the value in the Render UI
